### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by backfromhiatus** [abhaynayar/nand2tetris#4]
So I want to help u with this project
Can u pls give me write access? 
I'm really interested and I have many ideas with stuff like the fs io...

**Comment by abhaynayar** [comment]
Hi DiamondCoder1000,

Thanks for your interest in this repository!

Since I will not be updating this repository, I think it would be better if you fork it and work on it under your own profile.

I would of course like to help you in the future in case you have any technical doubts, but giving you write access is pointless, since I'm not contributing anymore.

So it'll be better for you to fork this code, and start fresh on your own, since there will be no contributions from my side.
